issuer: https://token.actions.githubusercontent.com
# binding to the specific branch
subject_pattern: '^repo:odigos-io(@84347062)?/odigos-opentelemetry-python(@842850155)?:(pull_request|ref:.*)$'

permissions:
  contents: read
