name: build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build local ES instrumentation
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          cd opentelemetry-instrumentation-elasticsearch
          hatch build
          pip install -e .
          cd ..

      - name: Install aggregator
        run: |
          pip install -e .

      - name: Run Python files directly to check for code errors
        run: |
          python -c "import initializer"
          python -c "import opamp"
