name: build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Vendor Forked instrumentations
        run: |
          make vendor-elasticsearch vendor-sqlalchemy vendor-aiohttp-server
  
      - name: Install package (editable mode)
        run: |
          pip install -e .

      - name: Smoke check imports
        run: |
          python -c "import initializer"
          python -c "import opamp"
          python -c "from opentelemetry.instrumentation.elasticsearch import ElasticsearchInstrumentor"
          python -c "from opentelemetry.instrumentation.sqlalchemy import SQLAlchemyInstrumentor"
          python -c "from opentelemetry.instrumentation.aiohttp_server import AiohttpServerInstrumentor"
